### ISSUE TITLE
Task List

### ISSUE THREAD

**Issue by Ekoda** [Ekoda/OpenForumProject#3]
- <h3>Frontend</h3>
- [x] Add mobile functionality
- [x] Add sign in / sign out frontend
- [x] Add notification functionality
- [ ] Add messaging functionality
- [ ] Add profile functionality 
- [x] Add response functionality
- [ ] Add view other profiles functionality
- [x] Fix input boxes
- [ ] Make sure large amounts of content scales well

- <h3>Backend</h3>
- [ ] Server
- [x] Database
- [x] Flask
- [ ] End to end encryption on messanges
- [ ] Add Profiles
- [ ] Forum room
- [ ] Add comments
- [ ] Add response
- [ ] Add ratings
